### ISSUE TITLE
stack test fails for jsaddle-0.3.0.2

### ISSUE THREAD

**Issue by juhp** [ghcjs/jsaddle#10]
I ran "stack test":

```
$ cabal unpack jsaddle-0.3.0.2
$ cd jsaddle-0.3.0.2
$ stack --resolver nightly init
$ stack test
jsaddle-0.3.0.2: test (suite: test-tool)

<command-line>:8:0:
     fatal error: dist/build/autogen/cabal_macros.h: No such file or directory
compilation terminated.
test-tool: test-tool: phase `C pre-processor' failed (exitcode = 1)

Test suite failure for package jsaddle-0.3.0.2
    test-tool:  exited with: ExitFailure 1
Logs printed to console
```

**Comment by mgsloan** [comment]
The issue is that the dist dir used by stack is located at `stack path --dist-dir`.  A hack to work around it. non-windows would be to symlink the path to `dist`.  Better to just have the test know it's being run by stack (check the `STACK_EXE` env var), and determine the dist path in the test.

**Comment by hamishmack** [comment]
I set it up to include `cabal_macros.h` and hard coded the path shown, but I don't think we actually need it.  I just thought it would be nice if in the future we used any of the `MIN_VERSION` macros (but I don't think the code does right now).  I think the lens has a proper solution [here](https://github.com/ekmett/lens/blob/master/Setup.lhs).

**Comment by hamishmack** [comment]
Please try 0.3.0.3

**Comment by juhp** [comment]
Thanks Hamish - it works for me.
