### ISSUE TITLE
Support GHC-8.8

### ISSUE THREAD

**Issue by phadej** [ghcjs/jsaddle#104]
If one allows

- `lens-4.18`
- `primitive-0.7`
- `time-1.9`
- `Cabal-3.0`
- `base-compat-0.11`
- `base-4.13` (`jsaddle-dom` setup)

 in `jsaddle`, `jsaddle-dom` and `jsaddle-warp`, they seem to compile fine with GHC-8.8.

**Comment by hamishmack** [comment]
These updated bounds should all be in hackage now
