### ISSUE TITLE
Nitpick: line duplicated

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/jsaddle#13]
Nitpick: this line is duplicated:

https://github.com/ghcjs/jsaddle/blob/master/src/Language/Javascript/JSaddle/Monad.hs#L36

**Comment by hamishmack** [comment]
Petty sure this was fixed.

File is now https://github.com/ghcjs/jsaddle/blob/master/jsaddle/src/Language/Javascript/JSaddle/Monad.hs#L36
