### ISSUE TITLE
Jsaddle with warp and websockets fails on firefox 57

### ISSUE THREAD

**Issue by tdimiduk** [ghcjs/jsaddle#54]
When running Jsaddle with the warp server, if you connect with firefox 57, the site will come up completely non-responsive, pegging a cpu to 100%.

**Comment by tdimiduk** [comment]
It turns out this issue is due to something goofy in early versions of firefox 57. If you have this problem, just update your firefox and it should go away

**Comment by ryantrinkle** [comment]
Thanks for documenting this!

**Comment by danwdart** [comment]
I find this is happening again on 86... I don't know why...
