### ISSUE TITLE
default to gtk3?

### ISSUE THREAD

**Issue by juhp** [ghcjs/jsaddle#9]
```
Preprocessing test suite 'test-tool' for jsaddle-0.3.0.1...
[1 of 1] Compiling Main             ( tests/DocTest.hs, dist/build/test-tool/test-tool-tmp/Main.o )
Linking dist/build/test-tool/test-tool ...
> /tmp/stackage-build8/jsaddle-0.3.0.1$ dist/build/test-tool/test-tool

src/Language/Javascript/JSaddle/Monad.hs:50:8:
    Ambiguous module name ‘Graphics.UI.Gtk.General.General’:
      it was found in multiple packages:
      gtk3-0.14.2@gtk3_LQL6kFfZwEeK6nO9fGGRs5 gtk-0.14.2@gtk_IthCkrmZyC49kGQu4HvvO2

src/Language/Javascript/JSaddle/Test.hs:22:8:
    Ambiguous module name ‘Graphics.UI.Gtk’:
      it was found in multiple packages:
      gtk3-0.14.2@gtk3_LQL6kFfZwEeK6nO9fGGRs5 gtk-0.14.2@gtk_IthCkrmZyC49kGQu4HvvO2

src/Language/Javascript/JSaddle/Test.hs:31:8:
    Ambiguous module name ‘Graphics.UI.Gtk.General.Enums’:
      it was found in multiple packages:
      gtk3-0.14.2@gtk3_LQL6kFfZwEeK6nO9fGGRs5 gtk-0.14.2@gtk_IthCkrmZyC49kGQu4HvvO2
```

**Comment by juhp** [comment]
"stack --resolver nightly build"s okay for me locally even with gtk3 and gtk installed, so I don't really understand why it failed in Stackage Nightly

**Comment by hamishmack** [comment]
This along with some other problems with the `cabal test` for this package have been fixed in 0.3.0.2 (just uploaded to hackage).  You may need to use xvfb-run to run `cabal test` though because it will hang trying to connect to X11 if it can't.

**Comment by juhp** [comment]
Thanks Hamish - it built fine, but unfortunately the testsuite timed out:

    jsaddle: Test suite timed out: jsaddle-0.3.0.2:test-tool

**Comment by juhp** [comment]
I'll open a separate ticket about the testsuite.

**Comment by juhp** [comment]
Ah I see your comment now about xvfb-run - I guess that explains the timeout in Stackage.
We generally ignore tests that need a system service/program running to work.
So I think I will just skip the tests in Stackage for now.
